---
version: '2.4'
services:
    
  mongo:
    container_name: mongo
    image: mongo:4.2
    ports:
      - 3306:3306
    networks:
      - app-network

  aik-app-api:
    build: aik-app-api
    ports: 
      - 3000:3000
    networks:
      - app-network

  aik-app-ui:
    build: aik-app-ui
    ports:
      - 3030:3030
    networks:
      - app-network
    depends_on:
      - aik-app-api
        
networks:
  app-network:
    driver: bridge